name: Java CI
on:
  push:
    branches:
      - master
      - '[4-9]+.[1-9]+.x'
  pull_request:
    branches:
      - master
      - '[4-9]+.[1-9]+.x'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '14']
    env:
      WORKSPACE: ${{ github.workspace }}
      GRADLE_OPTS: -Xmx1500m -Dfile.encoding=UTF-8
      RUN_TESTS_ONLY: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Optional setup step
        run: |
          [ -f ./setup.sh ] && ./setup.sh || true
      - name: Run Tests
        run: |
          (set -x; ./gradlew clean classes --no-daemon)
          (set -x; ./gradlew testClasses --no-daemon)
          ./gradlew --stop
          (set -x; ./gradlew grails-test-suite-persistence:test grails-test-suite-uber:test grails-test-suite-web:test --no-daemon)
          ./gradlew --stop
          (set -x; ./gradlew check -x grails-test-suite-persistence:test -x grails-test-suite-uber:test -x grails-test-suite-web:test --no-daemon)
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Run Assemble
        if: success() && github.event_name == 'push' && matrix.java == '8' && env.RUN_TESTS_ONLY == false
        run: ./gradlew assemble
      - name: Publish to repo.grails.org
        if: success() && github.event_name == 'push' && matrix.java == '8' && env.RUN_TESTS_ONLY == false
        env:
          SECRING_FILE: ${{ secrets.SECRING_FILE }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSPHRASE: ${{ secrets.SIGNING_PASSPHRASE }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          echo $SECRING_FILE | base64 -d > secring.gpg
          ./gradlew -Dorg.gradle.internal.publish.checksums.insecure=true -Psigning.keyId="$SIGNING_KEY" -Psigning.password="$SIGNING_PASSPHRASE" -Psigning.secretKeyRingFile="secring.gpg" publish
